Begin test suite
  test cases being run: 1
  Begin test case
    test case name: "exception_multiple_sections"
    file: "exception_multiple_sections.test.cpp"
    line: 3
    Begin test case run
      Begin section
        sections: 1
      Begin section
        sections: 1, 11
      Begin assertion
        expression: 11
        line: 9
      End assertion
        assertion success: true
        Unary assertion
          representation: 11
      Begin section
        sections: 1, 11, 111
      Begin assertion
        expression: 111
        line: 13
      End assertion
        assertion success: true
        Unary assertion
          representation: 111
      End section
        sections: 1, 11, 111
        section success: true
      End section
        sections: 1, 11
        section success: false
      End section
        sections: 1
        section success: false
    End test case run
      test assertions ran: 2
      test assertions passed: 2
      test assertions failed: 0
      test case run success: false
      exception type: class std::runtime_error
      exception message: "error section 11"
    Begin test case run
      Begin section
        sections: 1
      Begin section
        sections: 1, 12
      End section
        sections: 1, 12
        section success: false
      End section
        sections: 1
        section success: false
    End test case run
      test assertions ran: 0
      test assertions passed: 0
      test assertions failed: 0
      test case run success: false
      exception type: class std::runtime_error
      exception message: "error section 12"
    Begin test case run
      Begin section
        sections: 1
      Begin section
        sections: 1, 13
      Begin assertion
        expression: 13
        line: 26
      End assertion
        assertion success: true
        Unary assertion
          representation: 13
      End section
        sections: 1, 13
        section success: true
      End section
        sections: 1
        section success: true
      Begin assertion
        expression: 0 == 0
        line: 35
      End assertion
        assertion success: true
        Binary assertion
          first representation: 0
          second representation: 0
          operation: ==
    End test case run
      test assertions ran: 2
      test assertions passed: 2
      test assertions failed: 0
      test case run success: true
    Begin test case run
      Begin section
        sections: 2
      End section
        sections: 2
        section success: false
    End test case run
      test assertions ran: 0
      test assertions passed: 0
      test assertions failed: 0
      test case run success: false
      exception type: class std::runtime_error
      exception message: "error section 2"
    Begin test case run
      Begin assertion
        expression: 0 == 0
        line: 35
      End assertion
        assertion success: true
        Binary assertion
          first representation: 0
          second representation: 0
          operation: ==
    End test case run
      test assertions ran: 1
      test assertions passed: 1
      test assertions failed: 0
      test case run success: true
  End test case
    test assertions ran: 5
    test assertions passed: 5
    test assertions failed: 0
    test case success: false
End test suite
  test cases ran: 1
  test cases passed: 0
  test cases failed: 1
  test assertions ran: 5
  test assertions passed: 5
  test assertions failed: 0
  test suite success: false
